name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare package
        run: |
          bash scripts/pack.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/moofeeds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
